// ARRAYS ALLOW YOU TO STORE SEVERAL PIECES OF DATA IN ONE PLACE
// ARRAYS ARE ALWAYS ASSIGNED VALUES WITHIN [] UPON DECLARATION
// EVERY ELEMENT IN AN ARRAY IS SEPARATED BY A COMMA
// ELEMENTS OF DIFFERENT DATA TYPES CAN BE STORED WITHIN AN ARRAY

var ourArray = ["John", 23];

    // NESTED ARRAYS

        // NESTED ARRAYS, ALSO KNOWN AS MULTI-DIMENSIONAL ARRAYS, ARE THOSE WHERE ANOTHER ARRAY EXISTS WITHIN THEM. ONE ELEMENT IN THE ARRAY COULD THEREFORE BE ANOTHER ARRAY OF MANY ELEMENTS WITHIN THEM ITSELF, AS SEEN BELOW:

        var myArray = [["the universe", 42], ["everything", 101010]];

        // IN THE ABOVE, TWO ARRAYS ARE WITHIN THIS MULTI-DIMENSIONAL ARRAY, WITH TWO VALUES WITHIN IT THEMSELVES ie. TWO ARRAYS WITHIN ONE ARRAY, EACH WITH TWO ELEMENTS WITHIN THEM

    // ACCESSING ARRAY DATA WITH INDEXES

        