/*     Often, you will set data into a variable. A variable allows computers to store and manipulate data in a dynamic fashion, and is basically a label to point to the data. A variable is like a box, and it can be filled with anything/the data you want*/

// A VARIABLE CAN BE SET TO ANY OF THE DATA TYPES SEEN PREVIOUSLY

// THERE ARE THREE WAYS TO DECLARE A VARIABLE IN JS:

    // 1. var

    // THIS CAN BE USED ACROSS THE WHOLE PROGRAM AND CHANGED AT ANY POINT

    var myName = "Aman"; //DECLARING THE VARIABLE myName AND ASSIGNING IT A STRING TYPE (WHICH IS COMMON) VALUE OF Aman

    myname = 8;          // THE CONTENTS AND TYPE OF VARIABLE myName HERE CAN THEN ALSO BE CHANGED LATER

    // 2. let

    // THIS WILL ONLY BE USED WITHIN THE SCOPE OF WHERE IT WAS DECLARED
    
    let ourName = "freeCodeCamp";

    // 3. const

    // VARIABLE WHICH SHOULD NEVER AND CAN NEVER CHANGE ONCE SET. ATTEMPTING TO CHANGE THIS WILL RETURN AN ERROR

    const pi = 3.14;

    // THERE IS A DIFFERENCE BETWEEN ASSIGNING A VARIABLE AND DECLARING A VARIABLE:

        var a;      // THIS JUST DECLARES A VARIABLE, CALLED a
        var b = 2;  // THIS DECLARES A VARIABLE CALLED b, THEN ASSIGNS IT A DATA VALUE OF NUMBER. THE CONTENTS OF WHICH IS 2.

        // THE = IS THE ASSIGNMENT OPERATOR, SO LINE 30 MEANS THAT VARIABLE b IS BEING DECLARED AND ASSIGNED THE VALUE OF 2

        a = 7;      // SINCE a WAS ALREADY DECLARED PREVIOUSLY, HERE IT CAN JUST BE ASSIGNED A VALUE WITHOUT NEEDING TO DECLARE IT AGAIN

        b = a;      // HERE, THE CONTENTS OF a HAS BEEN ASSIGNED TO b, REPLACING THE VALUE 2 WITH THE VALUE 7

// (NB. IT IS GOOD PRACTICE TO END EACH LINE WITH A ;)

console.log(a);

