var myVar = 87;

// TO INCREMENT THE VALUE OF A (PREVIOUSLY DECLARED AND ASSIGNED) VARIABLE:

myVar = myVar + 1; // OUTPUTS 88

// THE QUICKER WAY OF ACHIEVING THIS:

myVar++; // OUTPUTS 89 (ACCOUNTING FOR ABOVE)
console.log(myVar);

// TO DECREMENT THE VALUE OF A VALUE:

var myVar = 11;

myVar = myVar - 1; // OUTPUTS 10

// THE QUICKER WAY OF ACHIEVING THIS:

myVar--; // OUTPUTS 9 (ACCOUNTING FOR ABOVE)
console.log(myVar);
